### Tạo comment cho 1 chapter
POST http://localhost:8081/api/v1/comment
Content-Type: application/json

{
  "chapterId": 35,
  "userId": 1,
  "content": "Good chapter! asdasdasdasd",
  "star": 5
}

### Lấy ra danh sách comment của 1 chapter
GET http://localhost:8081/api/v1/comment/chapter/35

### (Admin) Lấy ra danh sách comment
GET http://localhost:8081/api/v1/admin/comment

### (Admin) Lấy ra thông tin comment theo id
GET http://localhost:8081/api/v1/admin/comment/detail/1

### Đổi trạng thái comment cho 1 chapter
POST http://localhost:8081/api/v1/admin/comment
Content-Type: application/json

{
  "commentId": 1,
  "state": 2
}