POST http://localhost:8081/api/v1/users/register
Content-Type: application/json

{
  "username": "dsds",
  "password": "Ducvui2003#@#",
  "email": "Dong@gmail.com"
}
###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "a"
}
